Repository 2025-LIKELION-HACKATHON-NIEUNDASEOT/backend, pull requests merged in 2025-08, with the labels that each got.

#5 ✨ [Feat] region 관리 및 검색
  localadmin/initial_data.json
  localadmin/localadmin/settings/base.py
  localadmin/localadmin/urls.py
  localadmin/region/__init__.py
  localadmin/region/admin.py
  localadmin/region/apps.py
  localadmin/region/management/commands/load_regions.py
  localadmin/region/migrations/0001_initial.py
  localadmin/region/migrations/0002_alter_region_options_remove_region_code_and_more.py
  localadmin/region/migrations/__init__.py
  localadmin/region/models.py
  localadmin/region/serializers.py
  localadmin/region/tests.py
  localadmin/region/urls.py
  localadmin/region/views.py
  localadmin/requirement.txt
  localadmin/requirements.txt
Labels: 🐛 Fix, ⚙️ Setting, ✨ Feature, 🚀 Chore

#7 ✨ [Feat] AI 챗봇 기능과 챗봇 스크랩
  localadmin/chatbot/__init__.py
  localadmin/chatbot/admin.py
  localadmin/chatbot/apps.py
  localadmin/chatbot/migrations/0001_initial.py
  localadmin/chatbot/migrations/__init__.py
  localadmin/chatbot/models.py
  localadmin/chatbot/serializers.py
  localadmin/chatbot/services.py
  localadmin/chatbot/tests.py
  localadmin/chatbot/urls.py
  localadmin/chatbot/views.py
  localadmin/document/__init__.py
  localadmin/document/admin.py
  localadmin/document/apps.py
  localadmin/document/migrations/0001_initial.py
  localadmin/document/migrations/0002_documentscrap_created_at_alter_document_created_at.py
  localadmin/document/migrations/0003_remove_document_category_document_categories.py
  localadmin/document/migrations/__init__.py
  localadmin/document/models.py
  localadmin/document/tests.py
  localadmin/document/views.py
  localadmin/localadmin/settings/base.py
  localadmin/localadmin/settings/development.py
  localadmin/localadmin/settings/production.py
  localadmin/localadmin/urls.py
  localadmin/scrap/__init__.py
  localadmin/scrap/admin.py
  localadmin/scrap/apps.py
  localadmin/scrap/migrations/0001_initial.py
  localadmin/scrap/migrations/0002_chatbotscrap_category_alter_chatbotscrap_id.py
  localadmin/scrap/migrations/0003_remove_chatbotscrap_category_chatbotscrap_categories_and_more.py
  localadmin/scrap/migrations/0004_remove_chatbotscrap_categories_chatbotscrap_category.py
  localadmin/scrap/migrations/0005_rename_category_chatbotscrap_categories.py
  localadmin/scrap/migrations/__init__.py
  localadmin/scrap/models.py
  localadmin/scrap/serializers.py
  localadmin/scrap/tests.py
  localadmin/scrap/urls.py
  localadmin/scrap/views.py
  localadmin/user/serializers.py
  localadmin/user/utils.py
  localadmin/user/views.py
  requirements.txt
Labels: ♻️ Refactor, ⚙️ Setting, ✨ Feature

#10 ✨ [Feat] 유저 region 기능 연결 및 category 수정
  localadmin/user/admin.py
  localadmin/user/management/commands/create_initial_data.py
  localadmin/user/migrations/0005_remove_category_category_id_and_more.py
  localadmin/user/models.py
  localadmin/user/serializers.py
  localadmin/user/views.py
Labels: ♻️ Refactor, ✨ Feature

#13 ✨ [Feat] 공문 기본 API 구현
  localadmin/chatbot/migrations/0001_initial.py
  localadmin/chatbot/migrations/0002_initial.py
  localadmin/chatbot/migrations/0003_initial.py
  localadmin/document/admin.py
  localadmin/document/api.py
  localadmin/document/management/commands/fetch_dobong_docs.py
  localadmin/document/management/commands/fetch_gyeonggi_docs.py
  localadmin/document/management/commands/sync_seoul_api.py
  localadmin/document/migrations/0001_initial.py
  localadmin/document/migrations/0002_documentscrap_created_at_alter_document_created_at.py
  localadmin/document/migrations/0002_initial.py
  localadmin/document/migrations/0004_delete_documentscrap.py
  localadmin/document/migrations/0005_document_image_url.py
  localadmin/document/models.py
  localadmin/document/serializers.py
  localadmin/document/services/__init__.py
  localadmin/document/services/document_data_processor.py
  localadmin/document/services/gyeonggi_api_services.py
  localadmin/document/services/seoul_api_service.py
  localadmin/document/services/services.py
  localadmin/document/urls.py
  localadmin/document/views.py
  localadmin/localadmin/settings/base.py
  localadmin/localadmin/settings/development.py
  localadmin/localadmin/urls.py
  localadmin/scrap/migrations/0001_initial.py
  localadmin/scrap/migrations/0002_chatbotscrap_category_alter_chatbotscrap_id.py
  localadmin/scrap/migrations/0002_initial.py
  localadmin/scrap/migrations/0003_remove_chatbotscrap_category_chatbotscrap_categories_and_more.py
  localadmin/scrap/migrations/0004_remove_chatbotscrap_categories_chatbotscrap_category.py
  localadmin/scrap/migrations/0005_rename_category_chatbotscrap_categories.py
  localadmin/scrap/migrations/0006_documentscrap.py
  localadmin/user/migrations/0001_initial.py
  localadmin/user/migrations/0002_user_name_alter_usercategory_user_category_id_and_more.py
  localadmin/user/migrations/0003_remove_usercategory_user_category_id_and_more.py
  localadmin/user/migrations/0004_remove_usercategory_created_at_and_more.py
  localadmin/user/migrations/0005_remove_category_category_id_and_more.py
  localadmin/user/models.py
Labels: ✨ Feature

#14 ✨ [Feat] 푸쉬 알림, 알림 페이지 기능
  .github/workflows/deploy.yml
  .gitignore
  localadmin/chatbot/services.py
  localadmin/chatbot/views.py
  localadmin/localadmin/settings/base.py
  localadmin/localadmin/settings/development.py
  localadmin/localadmin/settings/production.py
  localadmin/localadmin/urls.py
  localadmin/notification/__init__.py
  localadmin/notification/admin.py
  localadmin/notification/apps.py
  localadmin/notification/firebase_service.py
  localadmin/notification/migrations/0001_initial.py
  localadmin/notification/migrations/__init__.py
  localadmin/notification/models.py
  localadmin/notification/serializers.py
  localadmin/notification/services.py
  localadmin/notification/signals.py
  localadmin/notification/tests.py
  localadmin/notification/urls.py
  localadmin/notification/views.py
  localadmin/scrap/admin.py
  localadmin/scrap/migrations/0003_alter_chatbotscrap_summary.py
  localadmin/scrap/migrations/0004_alter_chatbotscrap_summary.py
  localadmin/scrap/views.py
  requirements.txt
Labels: 📝 Docs, ♻️ Refactor, ⚙️ Setting, ✨ Feature, 💚 CI/CD

#16 ✨[Feat] 공문 세부 기능, 홈 기능
  .github/workflows/deploy.yml
  localadmin/backup.sql
  localadmin/backupwithlinkwithnowheredata.sql
  localadmin/document/api.py
  localadmin/document/management/commands/fetch_dobong_docs.py
  localadmin/document/management/commands/fetch_gyeonggi_docs.py
  localadmin/document/management/commands/fetch_jongno_docs.py
  localadmin/document/migrations/0003_document_keywords_document_purpose_and_more.py
  localadmin/document/migrations/0004_document_summary.py
  localadmin/document/migrations/0005_document_link_url.py
  localadmin/document/models.py
  localadmin/document/serializers.py
  localadmin/document/services/document_data_processor.py
  localadmin/document/services/jongno_api_service.py
  localadmin/document/services/seoul_api_service.py
  localadmin/document/services/services.py
  localadmin/document/urls.py
  localadmin/document/utils.py
  localadmin/document/views.py
  localadmin/document_backup.json
  localadmin/img_final.sql
  localadmin/localadmin/settings/development.py
  localadmin/localadmin/settings/production.py
  localadmin/notification/migrations/0002_alter_notification_content.py
  localadmin/notification/serializers.py
  localadmin/region/models.py
  localadmin/scrap/serializers.py
  localadmin/update_images.py
  localadmin/update_links.py
  requirements.txt
Labels: ✨ Feature

#18 ✨ [Feat] 스크랩 목록 응답에 doc id 추가
  localadmin/scrap/serializers.py
  localadmin/scrap/views.py
Labels: ✨ Feature

#20 🐛 [Fix] 예시 수정 및 document scrap 500 에러 수정
  localadmin/scrap/serializers.py
  localadmin/scrap/views.py
  localadmin/user/management/commands/create_initial_data.py
  localadmin/user/models.py
  localadmin/user/serializers.py
  localadmin/user/views.py
  trigger.txt
Labels: 🐛 Fix

#26 fix: upcoming_deadlines api에 has_deadline 필드 누락 수정
  localadmin/document/serializers.py
  localadmin/document/views.py
Labels: 🐛 Fix

#28 ♻️ [Refactor] ai 프롬프트 수정 및 region_id 응답 추가
  localadmin/chatbot/services.py
  localadmin/region/serializers.py
Labels: ♻️ Refactor

#30 🐛[Fix] serializers.py에 image_url 필드 반환 오류 수정
  localadmin/document/api.py
  localadmin/document/serializers.py
  localadmin/document/services/jongno_api_service.py
  localadmin/document/services/seoul_api_service.py
  localadmin/document/utils.py
  localadmin/document/views.py
Labels: 🐛 Fix
